const el={sessionForm:document.querySelector("#session-form"),messageForm:document.querySelector("#message-form"),identityPanel:document.querySelector("#identity-panel"),chatPanel:document.querySelector("#chat-panel"),messages:document.querySelector("#messages"),status:document.querySelector("#status"),identityError:document.querySelector("#identity-error"),input:document.querySelector("#message"),customerName:document.querySelector("#customer-name"),sessionLabel:document.querySelector("#session-label"),suggestions:document.querySelector("#suggestions"),restart:document.querySelector("#restart")};
let sessionId=null;let pendingMessage=null;
function setBusy(form,busy){form.querySelectorAll("button,input,textarea").forEach(node=>{node.disabled=busy})}
function timeLabel(){return new Intl.DateTimeFormat([],{hour:"2-digit",minute:"2-digit"}).format(new Date())}
function addMessage(kind,text,retry=false){const row=document.createElement("div");row.className=`message-row ${kind}`;const bubble=document.createElement("div");bubble.className="message";bubble.textContent=text;const meta=document.createElement("span");meta.className="message-meta";meta.textContent=timeLabel();bubble.append(meta);if(retry){const button=document.createElement("button");button.type="button";button.className="retry-button";button.textContent="Retry";button.addEventListener("click",()=>{if(pendingMessage)sendMessage(pendingMessage.text,pendingMessage.id)});bubble.append(button)}row.append(bubble);el.messages.append(row);el.messages.scrollTop=el.messages.scrollHeight}
function showTyping(){const row=document.createElement("div");row.className="message-row agent";row.id="typing";row.innerHTML='<div class="message typing" aria-label="Assistant is typing"><i></i><i></i><i></i></div>';el.messages.append(row);el.messages.scrollTop=el.messages.scrollHeight}
async function request(url,options){const response=await fetch(url,options);const payload=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.error?.message||`Request failed (${response.status})`);return payload}
el.sessionForm.addEventListener("submit",async event=>{event.preventDefault();el.identityError.textContent="";const customer=Object.fromEntries([...new FormData(el.sessionForm).entries()].map(([key,value])=>[key,value.trim()]).filter(([,value])=>value));if(!customer.phone&&!customer.email){el.identityError.textContent="Enter a phone number or email to continue.";return}setBusy(el.sessionForm,true);try{const result=await request("/v1/sessions",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({customer})});sessionId=result.session_id;el.customerName.textContent=result.customer.name;el.sessionLabel.textContent=`${result.customer.is_new?"New guest":"Welcome back"} · ${sessionId.slice(0,8)}`;el.identityPanel.hidden=true;el.chatPanel.hidden=false;addMessage("agent",`Welcome${result.customer.name?`, ${result.customer.name}`:""}. I can help with tables, menus, pre-orders, and your preferences. What would you like to arrange?`);el.status.textContent="Ready";el.input.focus()}catch(error){el.identityError.textContent=error instanceof Error?error.message:"Could not start a session."}finally{setBusy(el.sessionForm,false)}});
async function sendMessage(message,messageId=crypto.randomUUID()){if(!message||!sessionId||el.messageForm.dataset.busy==="true")return;pendingMessage={text:message,id:messageId};el.messageForm.dataset.busy="true";setBusy(el.messageForm,true);addMessage("user",message);el.input.value="";el.suggestions.hidden=true;el.status.textContent="Reception is thinking…";showTyping();try{const result=await request(`/v1/sessions/${sessionId}/messages`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({client_message_id:messageId,message})});document.querySelector("#typing")?.remove();addMessage("agent",result.message);pendingMessage=null;el.status.textContent=result.status==="needs_input"?"Waiting for your reply":"Ready"}catch(error){document.querySelector("#typing")?.remove();const detail=error instanceof Error?error.message:"The request could not be completed.";addMessage("agent",`${detail} You can retry this message.`,true);el.status.textContent="Message failed"}finally{el.messageForm.dataset.busy="false";setBusy(el.messageForm,false);el.input.focus()}}
el.messageForm.addEventListener("submit",event=>{event.preventDefault();sendMessage(el.input.value.trim())});
el.input.addEventListener("keydown",event=>{if(event.key==="Enter"&&!event.shiftKey){event.preventDefault();el.messageForm.requestSubmit()}});
el.input.addEventListener("input",()=>{el.input.style.height="auto";el.input.style.height=`${Math.min(el.input.scrollHeight,130)}px`});
el.suggestions.addEventListener("click",event=>{const prompt=event.target.closest("[data-prompt]")?.dataset.prompt;if(prompt)sendMessage(prompt)});
el.restart.addEventListener("click",()=>{sessionId=null;pendingMessage=null;el.messages.replaceChildren();el.chatPanel.hidden=true;el.identityPanel.hidden=false;el.suggestions.hidden=false;el.sessionForm.reset();el.identityError.textContent=""});
